"""empty message

Revision ID: 3101fb9ddb70
Revises: 37996ffdd3fb
Create Date: 2016-10-10 20:05:56.497076

"""

# revision identifiers, used by Alembic.
revision = '3101fb9ddb70'
down_revision = '37996ffdd3fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
