"""empty message

Revision ID: 37996ffdd3fb
Revises: 4ab30ab0706c
Create Date: 2016-10-10 19:51:08.336396

"""

# revision identifiers, used by Alembic.
revision = '37996ffdd3fb'
down_revision = '4ab30ab0706c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_votes_timestamp', 'votes', ['timestamp'], unique=False)
    op.add_column(u'questions', sa.Column('votat', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'questions', 'votat')
    op.drop_index('ix_votes_timestamp', 'votes')
    op.drop_table('votes')
    ### end Alembic commands ###
